name: Electron with Nuxt.js Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # You can adjust the Node.js version

    - name: Change working directory
      run: cd nuxt

    - name: Install Nuxt.js dependencies
      run: npm install

    - name: Build Nuxt.js app
      run: npm run build

    - name: Return to the root directory
      run: cd ..

    - name: Install Electron Builder
      run: npm install electron-builder -g

    - name: Install Electron app dependencies
      run: npm install

    - name: Build Electron app
      run: npm run electron:build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: electron-build
        path: dist_electron/


